### PR TITLE
Added missing libwebp files to update.sh

### PR DESCRIPTION
**Pull request by dimag0g**
Additional fix for issue #1234: missing files included in update script

### CODE REVIEW

**Comment by wolfbeast** [comment]
Please create a PR with only the relevant changes.

**Comment by dimag0g** [comment]
ooups, sorry. I didn't know PRs work like this.

**Comment by wolfbeast** [comment]
If you make a work branch/clone and create a pull request, it's a feature that you can update the pull request by pushing more commits to the same work branch. If you want to work on unrelated changes in the meantime, you should make a separate branch.

**Comment by dimag0g** [comment]
Thanks for being patient with me. I already googled this and I think I understood what to do. I'll undo the mess in my repo, then I'll make another PR. I want to discuss  the other changes on the forum to see if they are worth a pull request.

**Pull request closed without merging**
