### PR TITLE
Fix includes in dom for Mac build

### PR DESCRIPTION
**Pull request by adeshkp**
A couple of more includes are needed to build on master for Mac.

### CODE REVIEW

**Comment by mattatobin** [comment]
Could you please incorporate these changes suggested by @dbsoft which overlap with what you discovered for this PR?

https://pastebin.com/PhceAiTc

**Comment by adeshkp** [comment]
Yes, done. The fix for gamepad was missed because I have this feature disabled in my mozconfig file. Other changes are already there in the PR, and one has been committed by Moonchild already.

**Comment by mattatobin** [comment]
Thanks again @adeshkp as soon as something **else** is resolved I'll do a quick Windows build to be sure there isn't any sort of odd collision and merge this in.

We really appreciate you doing this!

**Comment by wolfbeast** [comment]
Tag #80

**Pull request merged**
