### PR TITLE
[PALEMOON] Moving About permissions component files from components/preferences/ to components/permissions/

### LINKED ISSUE #191: Move About permissions component files out of components/preferences
The files controlling `about:permissions` currently live in Pale Moon's `components\preferences` directory.
That is the wrong location for these files as it's a separate component and not related to preferences.

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
This resolves #191

---

I've created the new build (x32, Windows) - `Pale Moon UXP` - and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
LGTM but I'm not awake yet. Tobin?

**Comment by Lootyhoof** [comment]
Note that this involves `Theme Changes`.

This has already been dealt with on my side.

**Comment by wolfbeast** [comment]
> Note that this involves Theme Changes.

Already marked on the attached issue.

**Comment by wolfbeast** [comment]
Since Tobin seems to be MIA, I'm assuming this is ok from a casual inspection.

**Comment by mattatobin** [comment]
Looks fine to me.. very late r+

**Pull request merged**
