### PR TITLE
Implement Async Iteration in SpiderMonkey

### PR DESCRIPTION
**Pull request by g4jc**
Tag #1287. Please make tests on all platforms. Confirmed working on GNU/Linux.

### CODE REVIEW

**Comment by JustOff** [comment]
Could someone please suggest me the right way to test this using new comm-central repo style?

I guess it should be something like this:
1. Create test branch in UXP repo
2. Create test branch in Pale-Moon repo
3. Edit `.gitmodules` in Pale-Moon repo to point it to test branch in UXP repo
4. Remove `platform` folder in Pale-Moon repo, then init & update submodule
5. Build in Pale-Moon repo

Am I correct and maybe there is a simpler method?

**Comment by mattatobin** [comment]
You don't HAVE to use the submodule for development. So you can git submodule deinit and clone UXP directly to platform/ and manage it manually and not try and manage the submodule configuration which for you, you shouldn't be messing with.

The submodule is just very nice to use for doing builds as the commit pointer points where it should.

**Comment by JustOff** [comment]
@mattatobin, thank you for the clarification.

**Comment by JustOff** [comment]
I have to report that Pale Moon win32 builds just fine and passes the following [simple tests](https://www.codementor.io/@tiagolopesferreira/asynchronous-iterators-in-javascript-jl1yg8la1):

1. Async Iterators
```javascript
function asyncIterator() {
  const array = [1, 2];
  return {
    next: function() {
      if (array.length) {
        return Promise.resolve({
          value: array.shift(),
          done: false
        });
      } else {
        return Promise.resolve({
          done: true
        });
      }
    }
  };
}
```
2. for-wait-of Loop
```javascript
var iterator = asyncIterator();

(async function() {
    await iterator.next().then(console.log); // { value: 1, done: false }
    await iterator.next().then(console.log); // { value: 2, done: false }
    await iterator.next().then(console.log); // { done: true }
})();
```

3. Async Generators
```javascript
var asyncIterable = {
  [Symbol.asyncIterator]: asyncIterator
};

(async function() {
  for await (const item of asyncIterable) {
    console.log(item);
    // 1 2
  }
})();
```

**Comment by wolfbeast** [comment]
r+ from me. tested for possible regressions in ES6, ES2016+ and all looks good.

**Pull request merged**
