### PR TITLE
Deunify gfx

### PR DESCRIPTION
**Pull request by wolfbeast**
On-going de-unification work for #80 
This de-unifies /gfx in the tree. Tested buildability with Basilisk/Win64 and Pale Moon/Linux64 (gcc 7)

### CODE REVIEW

**Comment by wolfbeast** [comment]
Ping @g4jc @athenian200 for non-main build environments.

**Comment by g4jc** [comment]
Minor patch needed to get it working here:
```
diff --git a/gfx/gl/GLLibraryEGL.cpp b/gfx/gl/GLLibraryEGL.cpp
index 27bb1c42c..b8b53f7c2 100644
--- a/gfx/gl/GLLibraryEGL.cpp
+++ b/gfx/gl/GLLibraryEGL.cpp
@@ -24,6 +24,7 @@
 #include "prenv.h"
 #include "GLContext.h"
 #include "GLContextProvider.h"
+#include "gfxEnv.h"
 #include "gfxPrefs.h"
 #include "ScopedGLHelpers.h"
 #include "GLReadTexImageHelper.h"
```

**Comment by athenian200** [comment]
It seems to work okay on SunOS, too.

**Comment by wolfbeast** [comment]
Thanks! Merging.

**Pull request merged**
