### PR TITLE
Improve some button labels in preferences

### LINKED ISSUE #253: Improve some button labels in preferences
Options > "Privacy" tab > "remove individual cookies" link

Here are the current Pale Moon messages:
* when there is no search filter:
Remove Cookie - Remove All Cookies
* when there is a search filter:
Remove Cookie[s] - Remove All Cookies

I found it confusing ("a search filter is applied, if I click "Remove All Cookies", will it remove only the shown cookies or all the cookies?")

Then I gave a run with Firefox, and noticed they are using much less ambiguous messages:
* when there is no search filter:
Remove Selected - Remove All
* when there is a search filter:
Remove Selected - Remove All Shown

I think these clearer messages should be ported to Pale Moon.

https://bugzilla.mozilla.org/show_bug.cgi?id=1338036 - RESOLVED FIXED in Firefox 54

### PR DESCRIPTION
**Pull request by adeshkp**
This resolves #253

### CODE REVIEW

**Comment by vlakoff** [comment]
That's an impressive work, thank you very much!

**Comment by JustOff** [comment]
Could someone explain me why `removeSelectedCookies.label` uses plurals, although the value does not contain any number field, i.e `#1`?

It seems quite unnecessary and I would like to remove it to simplify localization.

**Comment by wolfbeast** [comment]
"Remove selected cookies" can pertain to 1 cookie or multiple cookies (depending on whether you have selected 1 cokie or multiple). The wording is different depending. (Remove selected cookie/Remove selected cookies). even if "cookie/cookies" is omitted, it can need different word formes for "selected" in other languages.

**Comment by JustOff** [comment]
Ok, thanks.

**Pull request merged**
