### PR TITLE
Reader Updates

### PR DESCRIPTION
**Pull request by Ascrod**
This is an update for the Reader component.

From here on I intend to update the Readability library files directly from the source instead of correlating with Firefox. This is because I noticed that some of Mozilla's automated codebase-wide style refactorings are touching the files specifically marked as "DO NOT MODIFY". Nothing breaking yet as far as I know, but it's not a risk I want to introduce.

### CODE REVIEW

**Comment by mattatobin** [comment]
Ascrod please use either the UXP or normalized mozilla bug commit style.

See UXP contribution guidelines for UXP style and commit history for the normalized mozilla bug style. Then force push the revised commits to your pr branch.

**Comment by Ascrod** [comment]
Aye aye, captain.

**Comment by mattatobin** [comment]
Does this require any fe changes to `Basilisk`?

**Comment by Ascrod** [comment]
Not really. The Android cleanup removes a little bit of unused UI, but nothing we care about and nothing that will affect themes. I checked.

**Pull request merged**
