### PR TITLE
Remove unboxed objects

### LINKED ISSUE #1030: Remove "unboxed" typed objects
Follow-up to #1017 

Disabling the "unboxed" object optimization gives us better performance in the real world. This has been baking without ill effects on unstable so we can remove the code now, simplifying typed object handling and reducing quite a bit of (complex) code in SpiderMonkey as a result.

We can use https://bugzilla.mozilla.org/show_bug.cgi?id=1505574 as a guideline.

### PR DESCRIPTION
**Pull request by wolfbeast**
This removes the rest of the disabled unboxed objects code (phase 2). Like with unboxed arrays, this could do with a check-build on Mac and Linux before merging. 

This resolves #1030 :tada:

### CODE REVIEW

**Comment by trav90** [comment]
Linking bustage on Linux:

```
 2:26.35     INPUT("StaticXULComponentsEnd/StaticXULComponentsEnd.o")
 2:26.35 
 2:26.35 ../../js/src/libjs_static.a(Unified_cpp_js_src24.o): In function `JSObject::swap(JSContext*, JS::Handle<JSObject*>, JS::Handle<JSObject*>)':
 2:26.35 /home/PM4Linux/REPO/UXP/js/src/jsobj.cpp:1501: undefined reference to `js::gc::StoreBuffer::putWholeCell(js::gc::Cell*)'
 2:26.35 /home/PM4Linux/REPO/UXP/js/src/jsobj.cpp:1502: undefined reference to `js::gc::StoreBuffer::putWholeCell(js::gc::Cell*)'
 2:26.35 /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: libxul.so: hidden symbol `_ZN2js2gc11StoreBuffer12putWholeCellEPNS0_4CellE' isn't defined
 2:26.35 /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: final link failed: Bad value
```

**Comment by mattatobin** [comment]
Are you going to have time to resolve this @trav90 ?

**Comment by wolfbeast** [comment]
More unified bustage, looks like. You probably need to `#include "StoreBuffer.h"` or `StoreBuffer-inl.h` in `jsobj.cpp`

**Comment by adeshkp** [comment]
Yes, you need `#include "gc/StoreBuffer-inl.h"` in `js/src/jsobj.cpp`. (on mac os at least)

**Comment by trav90** [comment]
@mattatobin yes I will take a look at this tonight.

**Comment by mattatobin** [comment]
Alright with that in I will do a test build on Windows and the Linux. @wixnix or @adeshkp can you provide me with a mac build of a UXP application preferably Pale Moon?

**Comment by wicknix** [comment]
Attempting a mac build now. Will report back when/if it completes.

**Comment by mattatobin** [comment]
@wicknix I also want the build for testing. While the macintosh I now have is not fit for building because of age, specs, and a few other issues relating to those.. I can do function testing. So I need a packaged build.

Other than that, please report to my channel tonight or in the next few days.. We have much to discuss.

**Comment by wicknix** [comment]
Success. Download here:
https://drive.google.com/file/d/1dcZUPA7sdY-7mELrKJ4rzdsqNsoq9kWe/view?usp=sharing

@mattatobin will do. Next week. The wife and i are leaving for vacation after work tomorrow for 9 days.

**Comment by mattatobin** [comment]
As near as I can tell the js engine is perfectly stable on all target platforms.

Based on this:

r+

**Comment by wolfbeast** [comment]
Merging! I'll be having a few beers tonight to celebrate. :tada: :beers:

**Pull request merged**
