### PR TITLE
CSS Grid Improvements

### LINKED ISSUE #1230: Back-computing percentages for intrinsic sizing causing negative percentages
Just go to https://lichess.org/editor/8/8/8/8/8/8/8/8_w_-_- and you will see the difference.

On latest Basilisk
Screenshot_20190924_132458

On Firefox 69.0
Screenshot_20190924_132628

Console doesn't show interesting info, but looking at css seems that something is not right with `grid-area`. Seems that works fine from Firefox 61.

### PR DESCRIPTION
**Pull request by g4jc**
Resolves #1230 and #1233

### CODE REVIEW

**Comment by mattatobin** [comment]
First off, allow me to thank you for this it seems very complete.

However, 2 things:

1) What are the test cases?
2) Will you please next time use our commit message format because in a few months I won't have any way of tracking these commits to anything.

**Comment by g4jc** [comment]
1) I backported the internal reftests and used a few of them, but I used the two test cases mentioned in the issues to verify proper working order:

* [Test 1](https://lichess.org/editor/8/8/8/8/8/8/8/8_w_-_-)

* [Test 2](https://www.mediamarkt.de/de/product/_motorola-moto-g7-plus-64-gb-viva-red-dual-sim-2522327.html

2) The reasoning for using the original commit names is to track them. I could squash the commits, but it makes it more difficult to trace them when certain bug situations pop up. (e.g. there was a bug in 1434478 part 6 which has been resolved. They had refactored and renamed parts of the file, which was totally uneeded.)

**Comment by mattatobin** [comment]
Buildablity, functionality and stability are looking good thus far but a cursory code review might still be warranted.

Unstables should also be produced for this.

**Comment by wolfbeast** [comment]
I can take a day out of my time off to do this.

**Comment by wolfbeast** [comment]
New unstables have been built and published with this change in, for testing.

**Comment by trav90** [comment]
Linux unstable has also been updated with this change in.

**Comment by mattatobin** [comment]
@trav90 Yeah.. about that.. Uhh.. We need to communicate. I apparently released an unstable too today.

**Comment by trav90** [comment]
@mattatobin I sent you a PM on the forum.

**Pull request merged**
