### PR TITLE
Implement ShadowRoot.activeElement. 

### PR DESCRIPTION
**Pull request by g4jc**
This does the required refactor and implementation for `ShadowRoot.activeElement`.
Deprot fixes and additional bug hunting courtesy @athenian200 :+1:

Tag #1375 - Shadow DOM v1

### CODE REVIEW

**Comment by mattatobin** [comment]
Your commit messages are ONCE AGAIN unacceptable. Please normalize the form and collapse parts if you are going to follow the bugzilla form.

**Comment by g4jc** [comment]
They cannot be collapsed without making it impossible to follow.

**Comment by mattatobin** [comment]
You have around 300 damned examples of how to handle the normalized bugzilla commit message form. You have NO excuse.

FIX THEM.

**Comment by g4jc** [comment]
**-r** due to Windows build failure. Patch being investigated and forthcoming.

**Comment by win7-7** [comment]
@mattatobin:

 @g4jc is good contributor to implement WebComponents to UXP. Please show some respect to @g4jc and be calm.

**Comment by mattatobin** [comment]
Please stay out of situations where you don't have all the facts and that does not concern you.

**Pull request closed without merging**
