### PR TITLE
Remove all C++ Telemetry Accumulation calls.

### PR DESCRIPTION
**Pull request by wolfbeast**
This creates a number of stubs and leaves some surrounding code that may be irrelevant (eg. recorded time stamps, status variables).
Stub resolution/removal should be a follow-up to this.

Because of the pervasive nature of almost 800 calls, also in hot paths, this will very likely noticeably improve performance of everything building on UXP.

Asking for review because this is a huge commit and I may have made some mistakes. Verification that this still builds on Linux is also important before merging.

Tag #21

### CODE REVIEW

**Comment by trav90** [comment]
Pale Moon builds successfully using GCC 7.3, though I did notice that there are an additional 67 compiler warnings generated. I don't see any issues after using this build for a short while (will continue testing). The browser definitely seems "snappier"!

Will build Basilisk later today.

**Comment by mattatobin** [comment]
I am doing Win64 builds, Basilisk first.

**Comment by wolfbeast** [comment]
@trav90 the additional compiler warnings are most likely for unused variables that should be cleaned up as a follow-up.

**Comment by trav90** [comment]
@wolfbeast agreed.

64-bit Basilisk builds and seems to run well with casual testing.

I need to test video playback and if that checks out I'd say everything is good as far as Linux is concerned.

**Comment by trav90** [comment]
I compared the build logs and unused variables are the cause of the higher number of compiler warnings. Youtube playback (1080p 60fps) is nice and smooth, and Youtube as a whole seems more responsive.

**Comment by wolfbeast** [comment]
@trav90 can you give me a filtered build log showing only the extra warnings, so I can use that as a guide to perform cleanup? MSVC doesn't really emit warnings for those.

**Comment by JustOff** [comment]
The only thing I will really miss is the startup data, like:

```
Simple Measurements
Property 				Value
start 					15
main 					94
selectProfile 				113
startupCrashDetectionBegin 		287
AMI_startup_begin 			300
XPI_startup_begin 			324
XPI_bootstrap_addons_begin 		534
XPI_bootstrap_addons_end 		846
XPI_startup_end 			846
AMI_startup_end 			852
XPI_finalUIStartup 			1616
createTopLevelWindow 			1670
firstPaint 				4690
firstLoadURI 				6611
sessionRestored 			6698
startupCrashDetectionEnd 		34876
totalTime 				302358
uptime 					5039
startupInterrupted 			0
js 					{"setProto": 448, "customIter": 86}
maximalNumberOfConcurrentThreads 	51
debuggerAttached 			0
startupWindowVisibleReadBytes 		68293350
startupWindowVisibleWriteBytes 		656485
startupSessionRestoreReadBytes 		68589214
startupSessionRestoreWriteBytes 	656485
savedPings 				1
activeTicks 				8738
pingsOverdue 				1 
```

**Comment by wolfbeast** [comment]
And why will you miss this, exactly? Wouldn't you rather have a faster start than a slower start with some geeky details that serve no purpose for the browser's operation?

**Comment by JustOff** [comment]
I used it a lot while tuning the browser internals, particularly when I was working with PMkit last year. It was also useful for me to know how fast the browser became when I [replaced the asynchronous reading of the session file with a synchronous one](https://github.com/MoonchildProductions/Pale-Moon/pull/1640). And sometimes I used this data for finding bad add-ons that slowed down the browser startup. 

Don't get me wrong, I'm not advocating against the whole telemetry removal, just noted that some part of it was quite useful and I will miss it.

**Comment by trav90** [comment]
@wolfbeast:

Full build log: https://gist.github.com/trav90/b043e9d9abddd7886d05876bbf80e908

All warnings (-Wunused-but-set-variable, -Wunused-variable, & -Wunused-function) displayed by GCC 7.3: https://gist.github.com/trav90/19cf4a2de35ac794f382b780074ea2e4

**Pull request merged**
