### PR TITLE
No longer expose crash reporter settings to users.

### PR DESCRIPTION
**Pull request by Peacock365**
Partially resolves https://github.com/MoonchildProductions/UXP/issues/1610

### CODE REVIEW

**Comment by mattatobin** [comment]
Stop.

**Comment by Peacock365** [comment]
What is going on with you? Crash reporter no longer exists, those settings are COMPLETELY, I emphasize COMPLETELY redundant.

**Comment by wolfbeast** [comment]
> Crash reporter no longer exists, those settings are COMPLETELY, I emphasize COMPLETELY redundant.

You didn't bother to do proper research. This PR is therefore incomplete and shouldn't just be tossed into the tree.
Just take one of these prefs:

http://xref.palemoon.org/moonchild-central/search?string=reportCrashURL&find=

leading to http://xref.palemoon.org/moonchild-central/source/basilisk/modules/PluginContent.jsm#1039

What do you think would happen with that code if the pref is removed and the caller (not having the default-supplied form of getting prefs) is not? It would break. You can't just pull this out without an issue signalling all UXP consumers because it will potentially affect all applications building on UXP, and may break them.

So terse responses from Tobin aside, it needs a lot more care to remove things if you want to contribute these kinds of changes.

**Comment by mattatobin** [comment]
I'd prefer not using those keywords at all.

**Pull request closed without merging**
