### PR TITLE
[PALEMOON] [frontend vs backend] Fix "Permissions Manager" and permissions

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Tag #121 

Tested:
- `Permissions Manager` and `Page Info`
- An example:
http://www.wickham43.net/flashvideo.php:
shows `undefined` instead of `[URL]`:

__Before:__
_undefined

__After:__
plugin_notification_ok

- Preferences: Buttons `Exceptions`
- Use permissions for `Web Notifications`

---

[Bug 996448 - Lazify the loading of PluralForm.jsm everywhere](https://hg.mozilla.org/mozilla-central/rev/b747c35ac54b)

Use "use strict" for aboutPermissions.js (better error search)

[Bug 1038811 - Push API - frontend integration](https://bugzilla.mozilla.org/show_bug.cgi?id=1038811)

[Bug 956151 - Remove the perm attribute in permissions.js](https://hg.mozilla.org/mozilla-central/rev/8c2acf0267ac)

[Bug 1006461 - Fix handling of permission notifications in preference dialogs](https://hg.mozilla.org/mozilla-central/rev/50afa8d7f066)

[Bug 431901 - Update preference dialogs to treat backspace and delete equivalently on Mac OS X](https://hg.mozilla.org/mozilla-central/rev/19c27603fded)

[Bug 574460 - Fix handling of permission deletion notifications in preference dialogs](https://hg.mozilla.org/mozilla-central/rev/ca8d8f284b99)

[Bug 340432 - Add the ability to cancel site permission changes](https://hg.mozilla.org/mozilla-central/rev/722f9df4cc1c)

[Bug 1137870 - Fix mismatching argument counts in permissions.js etc and remove unused treeUtils.js from cookies.xul](https://hg.mozilla.org/mozilla-central/rev/328350363afc)
\- partially (all others are already included)

[Bug 1039540 - Preferences: Disable the sorting of rows of sub-dialogs when right clicking](https://hg.mozilla.org/mozilla-central/rev/817390369f57)

[Bug 1170200 - Part 2: Update JavaScript consumers of nsIPermissionManager::Remove](https://hg.mozilla.org/mozilla-central/rev/d716c5d113d8)

[Bug 661831 - In about:permissions, make Ctrl+f focus the filter box instead of invoking the find bar](https://hg.mozilla.org/mozilla-central/rev/d6ea1920cbe2)

[Bug 1192458 - Consolidate push and desktop notification permissions](https://bugzilla.mozilla.org/show_bug.cgi?id=1192458) + depends on:
- [Bug 1216684 - Notification permissions cannot be granted/denied in private windows](https://bugzilla.mozilla.org/show_bug.cgi?id=1216684)
- [Bug 1216271 - Display a notification upon upgrade for users who currently allow notifications for at least one site](https://bugzilla.mozilla.org/show_bug.cgi?id=1216271)
- [Bug 1220884 - Friendlier strings for the notification upgrade UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1220884)
- [Bug 1221330 - Change the migration notification icon to the Firefox branding icon (per current release channel)](https://bugzilla.mozilla.org/show_bug.cgi?id=1221330)

[Bug 1173523 - Change nsIPermission to expose a principal rather than a host](https://bugzilla.mozilla.org/show_bug.cgi?id=1173523) + depends on:
- [Bug 1185365 - Cookie exceptions list doesn't accept URL starts with http:// or https://](https://bugzilla.mozilla.org/show_bug.cgi?id=1185365)
- [Bug 1189073 - Adding localhost:9091 cookie exceptions fails with console error](https://bugzilla.mozilla.org/show_bug.cgi?id=1189073)
- [Bug 1190175 - Offline app list is broken, no host name display](https://bugzilla.mozilla.org/show_bug.cgi?id=1190175)
- [Bug 1212610 - Unable to sort Sites in Permission dialogs](https://bugzilla.mozilla.org/show_bug.cgi?id=1212610)
- [Bug 1280775 - Crash in nsPermissionManager::RemovePermission when removing an already-removed website’s offline data](https://bugzilla.mozilla.org/show_bug.cgi?id=1280775)

[Bug 1288557 - Replace custom exceptions dialog (passwordManagerExceptions.xul) with usage of permissions.xul](https://bugzilla.mozilla.org/show_bug.cgi?id=1288557)

---

You add the label `Strings Changes` and `Theme Changes`, please.

### CODE REVIEW

**Comment by JustOff** [comment]
I can confirm this resolves the issue described in the example above, and it seems no side effects are observed, but the entire PR is quite large, and I don't know how to verify it completely.

**Comment by Lootyhoof** [comment]
A few questions/comments re: `Theme Changes`:

- Is `#push-notification-icon` actually used anywhere? It seems to have been defined in CSS, but nowhere else...
- Only `Push-16.png` actually seems to be utilised by the CSS. 
- The push icon styling wasn't applied at all for Windows.

**Comment by JustOff** [comment]
This results to `ReferenceError: gBrowserBundle is not defined[Learn More]  nsBrowserGlue.js:1423:9`.

**Comment by mattatobin** [comment]
The actual offending bits are on lines 1439 and 1440.. Preprocessing remember..

Also, JustOff is correct.. I'll add that real quick so @janekptacijarabaci doesn't have to make another pull request.

**Comment by janekptacijarabaci** [comment]
@mattatobin @JustOff 
Thank you. But I propose to extend it: 
https://hg.mozilla.org/mozilla-central/rev/0d5114f9b9d9

**Comment by mattatobin** [comment]
Go for it.. Just don't forget to include the lazy getter this time ;)

**Comment by FranklinDM** [comment]
I've noticed something:
The settings icon in the notification is missing (notifications now have it at the bottom-right corner).
capture
Also, we now show a [notification at startup](https://github.com/MoonchildProductions/UXP/pull/273/commits/79b88b30395c2a864b33ac90be804fc301d1d458) that notifications can be received from sites even if it is not open in a tab, but service workers are [disabled by default](http://xref.palemoon.org/uxp-trunk/source/modules/libpref/init/all.js#166) - which makes that not possible.

**Pull request merged**
