### PR TITLE
Restore throbber images to global skin.

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Tag #121

Ad https://forum.palemoon.org/viewtopic.php?f=63&t=19277

> In the customize palette the icon is gone, but the label can be seen. 
> If placed on a toolbar, Icon and label are both missing (though set to display icons+text).

---

I've created the new build (x32, Windows) - `Pale Moon UXP` - and tested.

__Not tested__: Linux, OSX

### CODE REVIEW

**Comment by JustOff** [comment]
I think that `webapps-*.png` part is unnecessary as these icons live in `chrome://browser/skin/` and theirs sources already exist in `application/palemoon/themes`.

**Comment by janekptacijarabaci** [comment]
Is (e.g.) this file (in PM 27) useless?:
`chrome://global/skin/icons/webapps-64.png`
(http://xref.palemoon.org/palemoon-trunk/search?find=%2Ftoolkit%2F&string=webapps-64.png)

Does it use any extensions?

**Comment by JustOff** [comment]
I guess all webbaps references in our tree are just leftovers from https://github.com/MoonchildProductions/Pale-Moon/pull/569.

**Comment by wolfbeast** [comment]
`webapps-*.png` is no longer used. No need to reintroduce the assets.
If extensions rely on them then they need to stop doing that and include their own graphics ;)

**Comment by janekptacijarabaci** [comment]
OK, thanks.

**Comment by JustOff** [comment]
Perhaps it's good occasion to remove all these [leftovers](http://xref.palemoon.org/uxp-trunk/search?string=webapps&find=application&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk) from `/application/palemoon/`?

**Comment by wolfbeast** [comment]
> Perhaps it's good occasion to remove all these leftovers from /application/palemoon/?

In a separate PR, please.

**Comment by JustOff** [comment]
> In a separate PR, please.

@janekptacijarabaci, will you do it, or me?

**Comment by janekptacijarabaci** [comment]
> @janekptacijarabaci, will you do it?

@JustOff 
Certainly not at the moment (and these days)...

**Comment by JustOff** [comment]
Well, then I will.

**Pull request merged**
