### PR TITLE
Initial MIPS Support

### PR DESCRIPTION
**Pull request by FlyGoat**
Issue: MoonchildProductions/UXP#1542

Mostly backport bugs.

### CODE REVIEW

**Comment by FlyGoat** [comment]
Updated commit messages, please review, thanks.

**Comment by mattatobin** [comment]
Someone finally read the contribution guidelines.. yay!

**Comment by mattatobin** [comment]
Tomorrow I will do some test builds for Windows/Linux and run it through Dromaeo and those javascript abominations they laughingly call websites these days.

**Comment by FlyGoat** [comment]
Do we have anything like continuous integration?

**Comment by mattatobin** [comment]
No, nor can we and we don't want it.

**Pull request merged**
