### PR TITLE
[PALEMOON] Reimplemented "Time Zone Information"

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Tags:
https://github.com/MoonchildProductions/Pale-Moon/issues/593
https://github.com/MoonchildProductions/Pale-Moon/pull/599
Issue #121

---

I've created the new build (x32, Windows) - `Basilisk` / `Pale Moon UXP` - and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
This has nothing to do with time zones...

**Comment by wolfbeast** [comment]
This also has nothing to do with front end integration (121)... 
Can you please be more careful how you name/link/describe issues?

**Comment by wolfbeast** [comment]
Tobin already merged it I see. well, that sucks. Sorry but I'll back this out and redo it so the commit history doesn't have confusing info.

**Comment by mattatobin** [comment]
I looked ar the code not the description because i can never trust it.. sorry.

**Comment by janekptacijarabaci** [comment]
> This also has nothing to do with front end integration (121)...

AFAIK: It is in `Preferences` - `General`:
preferences

But of course it's up to you.

**Comment by mattatobin** [comment]
The patch was good but your commit message was incorrect also this should eventually get implimented for basilisk too so the conditional was ok for now.

**Comment by wolfbeast** [comment]
Actually the `#ifdef MC_PALEMOON` is wrong. this is toolkit/platform stuff.

**Comment by janekptacijarabaci** [comment]
> commit message was incorrect

Yes, unfortunately, it was my fault...

> Actually the #ifdef MC_PALEMOON is wrong

So using `#ifdef MC_BASILISK` only?

**Comment by wolfbeast** [comment]
> So using `#ifdef MC_BASILISK` only?

No! It should apply to any application that downloads files on Windows.

**Comment by mattatobin** [comment]
Is the pref the only bit needed by the code then?

**Comment by wolfbeast** [comment]
All it ever did was make it prefable instead of always applying based on system.

**Pull request merged**
