### PR TITLE
Remove unboxed (checked branch)

### LINKED ISSUE #1090: Remove unboxed arrays
Similar to #1030, but with the difference that this code was never even enabled on release and is just dead code sitting there and adding unneeded complexity to SpiderMonkey/TraceMonkey/IonMonkey, as well as complicating the removal in #1030 by still requiring functions to remain in place for unboxed arrays.

Bug to use as guideline: https://bugzilla.mozilla.org/show_bug.cgi?id=1398768

### PR DESCRIPTION
**Pull request by wolfbeast**
This removes unboxed arrays from SpiderMonkey.

Resolves #1090 

This will need a checked build on Linux and Mac. @trav90 @wicknix

### CODE REVIEW

**Comment by trav90** [comment]
Build fine here on Linux. No issues seen with general browsing. Anything specific that needs tested?

**Comment by wolfbeast** [comment]
Functionality of array functions and making sure it doesn't crash with normal use.

**Comment by wicknix** [comment]
Same. Built fine on Mac. In limited testing I saw no issues.

**Comment by mattatobin** [comment]
Well since there seem to not be any target platform issues this can be merged into truck. Unless you think other applications like my own should be checked prior as well.

In any event, I suggest pushing unstable  builds pretty hard js wise between now and July. To make sure something non-obvious crops up.

**Comment by wolfbeast** [comment]
Thanks for building and testing!
Merging in.

**Pull request merged**
