### PR TITLE
Issues #816 / #802 - SpiderMonkey Tuneup

### PR DESCRIPTION
**Pull request by g4jc**
This is a large patch that rewrites the Parser and implements #816 (Rest/Spread) and #802 (Template Literals) in the Spider Monkey JavaScript engine.

### CODE REVIEW

**Comment by g4jc** [comment]
Audit and reviews welcome. This is a large patch that fundamentally alters the javascript engine so we will need some aggressive testing on all applications and platforms.

While these are backports, there are several key differences:

* We do not implement uneeded multi-threading. SpiderMonkey remains Single-Threaded.
* We do not implement DOM Promise Changes, using existing UXP code instead.
* We do not implement CharT changes
* We do not implement IonMonkey changes for hasOwn, using OwnProperty check from existing codebase instead.

The logic behind these patches and their dependency tree was logged here:
https://ethercalc.org/vye88tn5c4en

If anyone needs assistance setting up a debug build I have other patches available which were not included in this push.

**Comment by mattatobin** [comment]
Could you please report how binoc-central responds to this specifically mailnews?

**Comment by mattatobin** [comment]
Also, I can't even view the PR diff.. Nothing but pink unicorns...

**Comment by wolfbeast** [comment]
As additional background to this thread I have followed the patch progress, various re-bases and reworks of this code as WIP, and have kept a close eye on code in progress through private communication. Obviously, this needs investigation and extensive testing, but I would rather merge this in sooner rather than later to prevent any issues with code changes surrounding this, breaking the merge.

I suggest:
@adesh, @wicknix @mattatobin and myself make builds of this branch, check for obvious building/stability issues and report here if anything to report within the next 2 days. If good, bump the platform version, merge, toss it to the sharks on the unstable channel, and go from there.

**Comment by mattatobin** [comment]
General Javascript functionality and stability testing on Windows has gone very well for BinOC applications thus far.

@adeshkp or @wicknix could you provide me with Pale Moon Macintosh builds as soon as possible for the same testing?

**Comment by mattatobin** [comment]
The comm code paths and macintosh seem fully operational and stable. I am impressed and ecstatic. I think this is good to go to trunk and be shipped out on unstable!

Good work @g4jc!

**Comment by wicknix** [comment]
Guess i'm 10 minutes late to the party. Just built uxp-816 and added the menu bar name space commit to this build. No issues to report. Can grab from here to test if need be. 
https://drive.google.com/open?id=122hU-XExXdVwL12j330PdCAfeNNHIXDo

**Comment by wolfbeast** [comment]
Awesome. Considering this good to throw to the sharks!

**Comment by adeshkp** [comment]
Very cool job pulled off by @g4jc 
Great! :clap:

**Pull request merged**
