### PR TITLE
Added support of the appmenu for DevTools menuitems (optional)

### LINKED ISSUE #96: DevTools - Added support of the appmenu (optional)
Some preparation for `Pale Moon UXP`.

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
This resolves #96 → You add the label `Component: Devtools`, please

Reverted:
https://hg.mozilla.org/mozilla-central/rev/836da2d40b19
\+ adding some code

---

I've created the new build (x32, Windows) - `Basilisk`/`Pale Moon UXP` - and tested.

### CODE REVIEW

**Comment by mattatobin** [comment]
What happens when there isn't an appmenu?

**Comment by mattatobin** [comment]
Blocks #102

**Comment by janekptacijarabaci** [comment]
> What happens when there isn't an appmenu?

IMHO: The menu should be unified. And some users uses this menu - only:
https://github.com/MoonchildProductions/Pale-Moon/issues/1588

> Also, I want to keep devtools optional.. Keep that in mind.

IMHO: This removal (to an extension) does not change anything. They're still the same files, I just added the code for support the app menu. And if it does not exist, nothing will happen.

**Comment by mattatobin** [comment]
Works for me.. Proceed.

Also, stop with the "IMHO" please just state it.. Thanks! :)

**Pull request merged**
