### PR TITLE
Issue #21: Delete telemetry folder in toolkit/components folder

### PR DESCRIPTION
**Pull request by softwaretechone**

### CODE REVIEW

**Comment by wolfbeast** [comment]
For large toolkit removal requests, please organize your commits as follows:
1. Remove callers in code
    a. Remove callers from applications (one PR per application)
    b. Remove callers from various components (like DOM, gfx, netwerk; one PR per component unless it's something tightly intertwined or the overall code is little)
    c. Remove callers in toolkit and elsewhere low-level
2. Remove from config and build system
3. Remove physical files that are no longer referenced after 1 and 2 have been completed.

**Comment by softwaretechone** [comment]
Understood and thank you for the instructions. Also, I will issue a new pull request sometime today or tomorrow.

**Comment by mattatobin** [comment]
Please hold off on this for at least a week if you would. We are doing some things on our side that another codebase wide code change would collide with.

**Comment by softwaretechone** [comment]
Understood.

**Pull request closed without merging**
