### PR TITLE
Issue #1160 - Remove unused HotFix preferences

### PR DESCRIPTION
**Pull request by g4jc**

### CODE REVIEW

**Comment by wolfbeast** [comment]
Is that all? I thought there was more to be cleaned up?

**Comment by g4jc** [comment]
There's more, but I was asked to do it in parts and not touch the telemetry if I could help it.

**Comment by g4jc** [comment]
Leaving the bit in sync for now, just in case anyone does have a random hotfix in their profile, it tells sync to skip it. Removing this code would prevent sync from skipping it and potentially sync the hotfixes.

**Comment by wolfbeast** [comment]
@g4jc a kind request for future pull requests: please only open a pull request when you have all commits for it ready to be reviewed/merged. Opening a PR gives us a signal that you want something to be merged in, and if your code is still a work-in-progress then creating a PR at that time will give the wrong signal and potentially waste people's time reviewing code changes that are incomplete or not ready yet to be considered for adoption.

**Pull request merged**
