### PR TITLE
Don't allow STARTTLS when server sends PREAUTH 

### PR DESCRIPTION
**Pull request by g4jc**
Tag #1312

### CODE REVIEW

**Comment by mattatobin** [comment]
And this is? What is it for. Why is it here.

**Comment by wolfbeast** [comment]
I'm still in the process of getting sec bug access.

**Comment by wolfbeast** [comment]
The following was disclosed in public e-mail to me:

>"There isn't much in the bug, besides discussion how to fix it best. Basically a MITM could send PREAUTH to the client, causing the client to skip STARTTLS, and then the server would get to see the emails that the client is willing to save on the server, such as draft messages."

So basically STARTLS was previously ignored, but if used now aborts if PREAUTH is sent to err on the side of caution, IIUC.

No further action has been taken by the thunderbird team so far re: bug access. We can probably land this as-is without verification.

**Comment by mattatobin** [comment]
Thank you @wolfbest

**Comment by wolfbeast** [comment]
I've been given bug access, read through the discussion there and I can affirm that the solution landed is correct and covers all potential abuse scenarios (including passive leaking of data over unencrypted connections without MitM)

**Comment by mattatobin** [comment]
Thank you @wolfbeast

**Pull request merged**
