### PR TITLE
Remove code for sponsored "enhanced" tiles in NewTab page

### LINKED ISSUE #246: Remove code for sponsored "enhanced" tiles in NewTab page
Commit d2a0a16054771b4b0bee38ee7241a976bc1dac75 hard-disabled the use of sponsored tiles ("enhanced" tiles) in the NewTab page already.
The relevant code behind this "sponsored" (ad) tile system should be removed from our tree.

### PR DESCRIPTION
**Pull request by adeshkp**
#246 was pending due to an issue with page thumbnails which seems to have been resolved in the mean time, so it can proceed.

This also removes some strings related to enhanced newtab page.

After this, there will still be some code inside toolkit and Pale Moon frontend which relates to this and can go. Let me know if it's okay to clean that also.

Resolves #246

### CODE REVIEW

**Comment by mattatobin** [comment]
I am gonna test what you have thus far. But what else is there that is left after this?

**Comment by mattatobin** [comment]
r+ on changes thus far. However, we do want to resolve this issue with this PR so please identify whatelse needs done.

----

`DO NOT MERGE` .. yet.

**Comment by adeshkp** [comment]
Examples:
http://xref.palemoon.org/uxp-trunk/source/toolkit/modules/NewTabUtils.jsm#39
http://xref.palemoon.org/uxp-trunk/source/application/palemoon/components/newtab/page.js#51
http://xref.palemoon.org/uxp-trunk/source/application/palemoon/app/profile/palemoon.js#1080

I can make these extra changes also, but just wanted to keep them separate to be tackled later.

**Comment by mattatobin** [comment]
Do the Toolkit changes as a commit and the Pale Moon changes as a commit. I will review and hopefully call the issue done. k?

**Pull request merged**
