### PR TITLE
Add extensions.phoenixCompatibility pref

### PR DESCRIPTION
**Pull request by wolfbeast**
This changes the extension system's dual-GUID option so it is controlled
at run-time via preference `extensions.phoenixCompatibility`.
This defaults to `false` (don't allow Firefox-only extensions)

First part for #1318 -- still needs a migration path.

### CODE REVIEW

**Comment by mattatobin** [comment]
r- because it still needs ifdef'd and has changes I don't get.

**Comment by wolfbeast** [comment]
Sorry, I misunderstood your intention then about it being additional functionality.

What changes exactly don't you get?

**Comment by mattatobin** [comment]
This hack is for Pale Moon only it should not be in other applications. It makes no sense and having a preference existing means it can be flipped.

**Comment by wolfbeast** [comment]
Changes made. Please re-review.

Note, in case it's not clear this keeps the Firefox/native indicator hidden in the Add-on manager unless the pref is set to "true", because it wouldn't make any sense to restrict to Pale Moon extensions and still show the indicator.

**Comment by wolfbeast** [comment]
As discussed in IM this causes issues with disabled extensions not being re-enable-able.
Closing this PR for now.

**Pull request closed without merging**
